[[ZITSOL_1]]
arch = "aarch64"
git-tree-sha1 = "202a2e5c7a2e2bf8dd09bd4f69de04dd6a13f1a8"
libgfortran_version = "5.0.0"
os = "macos"

    [[ZITSOL_1.download]]
    sha256 = "e12cb32ceceba9d6f784a7376c59ef204fbe8d923c975af5505e75b342ab8c41"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "aarch64"
git-tree-sha1 = "c15517c8f91becdfdafbcce6ae2a240d2d7a53e4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "2cdea33f0e0a03659f4f2a0cd5ce687ed384207c2da73fec5da0a701ba281266"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "aarch64"
git-tree-sha1 = "c3858f0032c075838e5624b6c3ab95b973d79bf3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "92855234ec6f3c6c8b1997c21e077ebcb72122342933752821c71279d336350d"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "aarch64"
git-tree-sha1 = "140dc96f581c32f642862ed67505f0dea0d4940a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "448987d259cd3dd9dcd16a4c10081fc734dbfa21c8ecdd4a02072a238593f403"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "aarch64"
git-tree-sha1 = "ad06f05d8244abea4f42a8d3b68cb7c7717ac1f1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "b4807bba305a15b3ccf639fc70cd8e8e04d041e38c31a6b404ae6f96f79fdb8b"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "aarch64"
git-tree-sha1 = "a327addc46dcf535b00f1d1883b52c727e098ee4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "7ec1b428b843791e0b3d2f5d78e569c82d473e16761b7661d3c200018e470f02"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "aarch64"
git-tree-sha1 = "3d37d09ae4191ac28cb954680d1758875ca57bac"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "6cf8dd25eca36c48f810523902041280a4e41454b089eb9037aa3a0c4516f625"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b8077ef92565726c93f2f4394d6212fde992aeb4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "6cb20053a76c8df749314cc292925d02bef3490a203978bf1b1cf938cbff58aa"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "16b3ad688eee59b9c65b99c3fe14f85a74f2bc28"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "ed8470f0a1a73b642d1aea0d801f4f74770a1836f6ec406a6b8dee5106d8b72e"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ae6011e9ab24fc7711ef276290f7ffe356cd914"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "fcae1c6413f51b365382b7a6e7cda59c8b476d8b78f239b75744a51be7c4866e"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae1078f893982de1196414c252c1e4c02d0aa567"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "82fda68a615663b17e816b5091df8d2895b69e8ff7a2c250fce086b636fe9112"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "78277bf5d7210d13fc64d161e7bb6e11d67d8176"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "a25d37b587645d6322b1edae955e689fa0fc9c44ef2acb05d410e36f4d6bb39f"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "80a6cb25e8db72cb1d321761dbc6492d64655afa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "b957406b0a6dd8970d8ad843713e0f50b89ec8d9fbe81e923428b7d1a2614947"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "69e7babbbe63dbddc10010aa05419007f2402d77"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "9d55f81015e56f33b5353d51d76712699b930b3cd009322c975c7aea7adfe320"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d09ef7c2fec07d0a57ca0207c999c9745d7084e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "324c54fceb7182475249390303243cc19c166da6baa4fc04834c0cb2c1fd2c80"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc8686f7908eaad1147e7b59edda96c40f43a35d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "efa9b3f2f4ae18c258aae47aa0efd9143f8a7404c45c706c17ad154c62cc2c8c"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7222d206fd80c968ca5628e70bb3c38a71ea46a9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "0494d789e74eae1e013ecc2e2fd5f1b411c4627881e6e4af8f0c918d652b5a05"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "13462f9137b0337d9e8029884c7df1eb36be130c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "e615387474264ba1a1d735aa027763830900435fbdbc73f2da0b7ed438be2b12"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bdd80c369a055948e93dba514818368d2c08a01"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "844e78d7a44bb7c6b3354e6cf892387a845d5c2762ba6a3389c348632bf667f9"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "e3756adb61dc5901b7c3ef2afff92620b0648008"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "5f2f1cea6125fd19d32fb66d8a59f5127962fa86b5b041475d2fe31bf9fed2a1"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-linux-gnu-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "44c46c62920fff4d8c9c542715c8def4dcdd8cc7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "d81ec6a8814be983b5a26e0d82a8152c0bc31963e23f35108d6d3f4d8f18ee12"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-linux-gnu-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "7be2ed6ecb8d115b5ff9385920ee804f9346b65b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "cfc25c9ff00f5c998879fc9f52fb73c8c77539cda89f4a9f243d25b59bb7e6c4"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "54352b1f267cd1c5ee43db21668f3c32ccb9bbda"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "9eda96feb605e91f2dd15b301ccaee9e1b0fd76b86a43ca0c5f7d160f7e0b777"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-linux-musl-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "ce82913c164ce6c383a43666524839f9f0e84012"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "b6e18ed823d76f8bcfa9cf580fa3f9e5a76b0ece62d5a4595a638de46e179701"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-linux-musl-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "59e65fd40e189184b31769e747ef20ad719046c1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "603dd07db6567e8e0e9ff7c3c094d7082515ed18473473cbc4f74ad01fd89494"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "067f389a685881a6568c468a3502d41b8bc05b84"
libgfortran_version = "3.0.0"
os = "windows"

    [[ZITSOL_1.download]]
    sha256 = "ad2565d8f98b9989d97f73e2eb0d84eea7372f7862242c96f7b99f996c0119f6"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "7c9a87415f4f2462cb4918eb73191d9f79eed3dc"
libgfortran_version = "4.0.0"
os = "windows"

    [[ZITSOL_1.download]]
    sha256 = "86f4174911518a76816a4079d06dd666c6fb7ae4e65be7be753d6c1ad9de41be"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "i686"
git-tree-sha1 = "91db31659b8086d9c38afea8ca6b77b494d8a2ed"
libgfortran_version = "5.0.0"
os = "windows"

    [[ZITSOL_1.download]]
    sha256 = "0b3e0cb03ade9b8acf73908fcffdecc76f5813c7be8d20f920a570bc8a44249a"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "powerpc64le"
git-tree-sha1 = "8acc4c796a30ea1c9bc807cb0008a4d21cfce163"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "513c2c311468f0240f7b03045f0be84de7e9ac2e7f650b60a4857f030ff009e8"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "powerpc64le"
git-tree-sha1 = "8f9a05d85bd8b451e1c52dba7a25045aee9eb9ff"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "7cd62cec12cd0d50fd8553dd8a18ac9c9553b0fec72297a3a7839c95091b5a4a"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "powerpc64le"
git-tree-sha1 = "bbe651b8b315afe62b60cdc851c8cf9ee46fc669"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "20a06b896ef7f4c60d061e4b692903c245a281a78aac9856790876a1210652f0"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "ddf840f0273601f1a7d42e5a09710a93b8df6318"
libgfortran_version = "3.0.0"
os = "macos"

    [[ZITSOL_1.download]]
    sha256 = "adf2b4876c743d3fe73108778ef04a0f22c3a59a0ac3f714b1a5c0cf22d49068"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "3e5e055cc0d863b5b170d796fbb442b7a837ae83"
libgfortran_version = "4.0.0"
os = "macos"

    [[ZITSOL_1.download]]
    sha256 = "143f35388f35f085f757f7ab42848b681e94d3b363c3c156a8ffd66f81153958"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "373d2d7eddb011334694645851c3dea56c040d2d"
libgfortran_version = "5.0.0"
os = "macos"

    [[ZITSOL_1.download]]
    sha256 = "d23f356b6da0f50611b73cf3bfa9c5190a3aedc0920524351df208e1763b5545"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "8eed9cf634bd4aa386ebda3058b620515fef5593"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "e6c3baa6b096add8a09f951d1c6c16d4085de5da7bd01960797a40e8d20c1e6a"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "7cefe812e655b20e5c0cbe54ed89fb2af60c93d1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "70785a713ca2cba73b8a0936989aed1f77076724d5278ac51e61c7a6c426aa8f"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "68c8dab5420d1244d433629e4c17b51f48a1c70d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "cbce75691fa5d173a21aee21fb14348e520f0b752b0176ebfe2a742e27a05886"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "614873003520caa5b381bc0de46d57cb65797b76"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "419c423263236fbe89adf6c7e1e9a9cd3f2c7417c4995d5b3ed5d4d69f657baf"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "1689120c548eacae6a7cc470988e44d33367f8fc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "40ad732f83a95f1efb6ef27d929f6a06d5e305fa14d9d9dacc4f7335410885b8"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "63f33cedfe1a74530cb9bbf629844d09bb752fab"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ZITSOL_1.download]]
    sha256 = "0c90a4825597ff564ff751bbe6f93785d21ca799884d78f2f0f61a07d19f2b43"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "d883438df020a35c004bc64b5234291d0603a2ec"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[ZITSOL_1.download]]
    sha256 = "86addd291e7a640a70d04aa20497bf40e71718d80d51ac196862775ffeb65516"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "3d76cac59d00dc2dc44a60ea8905087c79a467a3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[ZITSOL_1.download]]
    sha256 = "9976bf19b3c15244a2a8b465776715158298fa05e58cac52343173adfffd828c"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "1251f1d9c6a77a182a9534b15dfccfbaff233dc0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ZITSOL_1.download]]
    sha256 = "ae2f7fef1c4a5fdbcfba665dc02db336515314e5f8a333e93ac5e8d1594ea63f"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "d87f01348c9f62ee463168749741dfe6d1528285"
libgfortran_version = "3.0.0"
os = "windows"

    [[ZITSOL_1.download]]
    sha256 = "bd41e27736cbf60ee44bb04767ef47dfb1eb0cabc8a574ac9f5092cc0338003e"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "ccd06a2647dfa725b05b9bfa35e26bd908827426"
libgfortran_version = "4.0.0"
os = "windows"

    [[ZITSOL_1.download]]
    sha256 = "cd6f20ffc176e05e0518d5921c3af9d9581ea4ebee3f52995da0291c2b57b987"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[ZITSOL_1]]
arch = "x86_64"
git-tree-sha1 = "26c3afef706b4e812a32c809ed9d7d7a8c6e81f8"
libgfortran_version = "5.0.0"
os = "windows"

    [[ZITSOL_1.download]]
    sha256 = "45d0079251f9e02bc5d088a0bef0fc5c0e67877e5f4fef6ec283024ba907142c"
    url = "https://github.com/JuliaBinaryWrappers/ZITSOL_1_jll.jl/releases/download/ZITSOL_1-v0.1.1+0/ZITSOL_1.v0.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
